### ISSUE TITLE
details view doesn't update

### ISSUE THREAD

**Issue by timofei7** [jcjiang/where2meet#1]
if i create a location and then look at other locations the details view shows me the one i created and doesn't update state

![simulator screen shot - iphone x - 2017-12-21 at 13 49 16](https://user-images.githubusercontent.com/1221134/34270758-4d0cb7d6-e657-11e7-8cf0-29b0087df48f.png)

**Comment by jcjiang** [comment]
Now wipes current/temporary state whenever modal is closed, which will work for all cases once the modal issue is solved.  Because the marker component, as it exists in the database/AirBnb API, possesses set props that do not include the name/location/time, I generate a description as a result of my own custom parameters vs. having name/location/time as parts of my individual marker states.
